// ═══════════════════════════════════════════════════════════════
//  MACRO v2 — Card Definitions
//  50 cards across 5 Trading Desks. Each card has real-world
//  transmission logic baked into its sensitivities and effects.
// ═══════════════════════════════════════════════════════════════

import { CardDef } from './types';

// ─── Rates Desk (10 cards) ───────────────────────────────────

const RATES_CARDS: CardDef[] = [
  {
    id: 'rates_powell',
    name: 'Jerome Powell',
    desk: 'rates',
    type: 'position',
    lane: 'rates',
    basePnL: 6,
    cost: 4,
    sensitivities: { rate: 3, risk: -1 },
    indicatorChanges: { rate: -2 },
    laggedIndicatorChanges: { risk: 1 },
    description: 'Fed Chair. Deploy: Rate −2 now, Risk +1 next turn (forward guidance calms markets).',
    chain: 'Powell speaks → Markets price in dovish pivot → Rates fall → Confidence builds (lagged)',
    art: '🏛️',
    keywords: ['fed', 'official'],
  },
  {
    id: 'rates_volcker',
    name: 'Paul Volcker',
    desk: 'rates',
    type: 'quickplay',
    lane: 'rates',
    basePnL: 0,
    cost: 3,
    indicatorChanges: { rate: 3 },
    laggedIndicatorChanges: { inflation: -3 },
    regimeEffects: [{
      condition: { indicator: 'rate', op: '>=', value: 8 },
      label: 'Over-tightening',
      indicatorOverride: { rate: 3, risk: -4 },
      description: 'Hiking into already-tight conditions breaks the economy.',
    }],
    description: 'Volcker shock: Rate +3 now, Inflation −3 next turn. The pain works, but slowly.',
    chain: 'Volcker hikes aggressively → Rates spike → Inflation expectations break (lagged) → Economy slows',
    art: '🔨',
    keywords: ['fed', 'historical'],
  },
  {
    id: 'rates_yci',
    name: 'Yield Curve Inversion',
    desk: 'rates',
    type: 'catalyst',
    lane: 'rates',
    basePnL: 0,
    cost: 2,
    indicatorChanges: { risk: -3 },
    description: 'Inverted curve signals recession ahead.',
    chain: 'Short rates exceed long rates → Recession signal flashes → Risk appetite collapses',
    art: '📉',
    keywords: ['signal'],
  },
  {
    id: 'rates_qe',
    name: 'QE Infinity',
    desk: 'rates',
    type: 'quickplay',
    lane: 'rates',
    basePnL: 0,
    cost: 3,
    indicatorChanges: { rate: -2, risk: 3 },
    laggedIndicatorChanges: { inflation: 2 },
    regimeEffects: [{
      condition: { indicator: 'rate', op: '<=', value: 1 },
      label: 'Pushing on a String',
      indicatorOverride: { rate: -1, risk: 1 },
      description: 'QE at near-zero rates has diminished returns — liquidity trap.',
    }],
    description: 'Money printer goes brrr. Risk +3 now, Inflation +2 next turn (QE inflation is lagged).',
    chain: 'Fed buys everything → Rates pinned at zero → Liquidity floods markets → Inflation builds (lagged)',
    art: '🖨️',
    keywords: ['fed', 'stimulus'],
  },
  {
    id: 'rates_10y',
    name: '10-Year Treasury',
    desk: 'rates',
    type: 'position',
    lane: 'rates',
    basePnL: 4,
    cost: 2,
    sensitivities: { rate: 2, inflation: -1, risk: -1 },
    description: 'Benchmark bond. Gains from rate hikes, loses to inflation.',
    chain: 'Treasury yields move with policy rates → Inflation erodes real returns → Safe haven in risk-off',
    art: '📜',
    keywords: ['bond', 'stable'],
  },
  {
    id: 'rates_tips',
    name: 'TIPS Position',
    desk: 'rates',
    type: 'position',
    lane: 'rates',
    basePnL: 3,
    cost: 2,
    sensitivities: { inflation: 2, rate: 1 },
    description: 'Treasury Inflation-Protected Securities. Hedges inflation.',
    chain: 'Inflation rises → TIPS principal adjusts upward → Real yield preserved',
    art: '🛡️',
    keywords: ['bond', 'inflation-linked'],
  },
  {
    id: 'rates_yellen',
    name: 'Janet Yellen',
    desk: 'rates',
    type: 'position',
    lane: 'rates',
    basePnL: 5,
    cost: 3,
    sensitivities: { rate: 2, usd: 1 },
    indicatorChanges: { usd: 2 },
    description: 'Treasury Secretary. Deploy: USD +2. Benefits from strong dollar policy.',
    chain: 'Yellen signals strong dollar → USD strengthens → Treasury demand rises',
    art: '🏦',
    keywords: ['official'],
  },
  {
    id: 'rates_bailout',
    name: '2008 Bailout',
    desk: 'rates',
    type: 'catalyst',
    lane: 'rates',
    basePnL: 0,
    cost: 3,
    indicatorChanges: { rate: -3 },
    laggedIndicatorChanges: { risk: 3 },
    description: 'Too big to fail. Rate −3 now, Risk +3 next turn (confidence returns slowly).',
    chain: 'Banks rescued → Fed slashes rates to zero → TARP stabilizes → Confidence returns (lagged)',
    art: '💰',
    keywords: ['crisis', 'historical'],
  },
  {
    id: 'rates_repo',
    name: 'Repo Market Stress',
    desk: 'rates',
    type: 'catalyst',
    lane: 'rates',
    basePnL: 0,
    cost: 1,
    indicatorChanges: { risk: -2 },
    description: 'Plumbing breaks. Overnight funding markets seize.',
    chain: 'Repo rates spike → Banks hoard cash → Fed forced to intervene → Systemic risk flares',
    art: '🔧',
    keywords: ['crisis'],
  },
  {
    id: 'rates_duration',
    name: 'Duration Play',
    desk: 'rates',
    type: 'position',
    lane: 'rates',
    basePnL: 2,
    cost: 1,
    sensitivities: { rate: 4, inflation: -2 },
    description: 'High-conviction long-duration bet. Massive rate sensitivity.',
    chain: 'Long-dated bonds move violently with rate expectations → Inflation is the enemy of duration',
    art: '📏',
    keywords: ['bond'],
  },
  {
    id: 'rates_hy',
    name: 'High Yield Bond',
    desk: 'rates',
    type: 'position',
    lane: 'rates',
    basePnL: 5,
    cost: 3,
    sensitivities: { rate: -1, risk: 2, inflation: 1 },
    regimeEffects: [{
      condition: { indicator: 'risk', op: '<=', value: 2 },
      label: 'Credit Crunch',
      pnlModifier: -6,
      description: 'Credit spreads blow out in panic — junk bonds become junk.',
    }],
    description: 'Corporate credit. Higher yield than treasuries but blows up in crisis.',
    chain: 'Credit spread compresses in risk-on → Yield-hungry investors pile in → Panic reverses everything',
    art: '💳',
    keywords: [],
  },
  {
    id: 'rates_reit',
    name: 'REIT',
    desk: 'rates',
    type: 'position',
    lane: 'rates',
    basePnL: 5,
    cost: 3,
    sensitivities: { rate: -3, inflation: 1, risk: 1 },
    description: 'Real estate investment trust. Income-generating but crushed by rate hikes.',
    chain: 'Low rates fuel mortgage demand → Property values rise → Rate hikes freeze the market',
    art: '🏢',
    keywords: [],
    turnEffect: 'dividend',
  },
  {
    id: 'rates_tbill',
    name: 'T-Bill / Cash',
    desk: 'rates',
    type: 'position',
    lane: 'rates',
    basePnL: 1,
    cost: 0,
    sensitivities: { rate: 1 },
    description: 'Risk-free rate. Free to deploy. Earns more as rates rise. Cash is a position.',
    chain: 'Park capital in short-duration treasuries → Earn the risk-free rate → Zero downside → Opportunity cost of doing nothing',
    art: '💵',
    keywords: ['stable'],
  },
  {
    id: 'rates_cdo',
    name: 'CDO',
    desk: 'rates',
    type: 'position',
    lane: 'rates',
    basePnL: 9,
    cost: 4,
    sensitivities: { rate: -2, risk: 1 },
    regimeEffects: [{
      condition: { indicator: 'risk', op: '<=', value: 3 },
      label: 'Toxic Tranches',
      pnlModifier: -10,
      description: 'Hidden risk materializes — the senior tranches were junk all along.',
    }],
    description: 'Collateralized debt obligation. Looks safe. High yield. Until it isn\'t.',
    chain: 'Mortgages pooled and sliced → Rating agencies bless it AAA → Risk is hidden, not eliminated → Crisis reveals the truth',
    art: '🧊',
    keywords: [],
    quarterEndEffect: 'destroy_40',
  },
  {
    id: 'rates_convertible',
    name: 'Convertible Bond',
    desk: 'rates',
    type: 'position',
    lane: 'rates',
    basePnL: 4,
    cost: 2,
    sensitivities: { rate: -2, risk: 2 },
    description: 'Bond with equity upside. Gets bond safety + converts to equity if things go well.',
    chain: 'Fixed coupon provides floor → Equity option provides upside → Best of both worlds in moderation',
    art: '🔄',
    keywords: [],
  },
  {
    id: 'rates_short_bonds',
    name: 'Short Bonds',
    desk: 'rates',
    type: 'position',
    lane: 'rates',
    basePnL: -1,
    cost: 1,
    sensitivities: { rate: -3, inflation: 2 },
    description: 'Bet against bonds. Profits when rates fall and inflation rises.',
    chain: 'Short treasury futures → Rates drop → Bond prices rise against you → But inflation erodes real returns',
    art: '📉',
    keywords: ['short'],
  },
];

// ─── Equities Desk (10 cards) ────────────────────────────────

const EQUITIES_CARDS: CardDef[] = [
  {
    id: 'eq_buffett',
    name: 'Warren Buffett',
    desk: 'equities',
    type: 'position',
    lane: 'equities',
    basePnL: 5,
    cost: 3,
    sensitivities: { risk: 1 },
    description: 'Oracle of Omaha. Immune to catalysts. Grows +1/turn.',
    chain: 'Value investing compounds quietly → Buffett sits through volatility → Long-term gains',
    art: '🎩',
    keywords: ['immunity'],
    turnEffect: 'growth_1',
  },
  {
    id: 'eq_concentrated',
    name: 'Concentrated Bet',
    desk: 'equities',
    type: 'position',
    lane: 'equities',
    basePnL: 10,
    cost: 5,
    sensitivities: { rate: -3, risk: 3 },
    regimeEffects: [{
      condition: { indicator: 'rate', op: '>=', value: 7 },
      label: 'Rate Shock',
      pnlModifier: -10,
      description: 'High rates destroy leveraged growth bets — valuations collapse.',
    }],
    description: 'Glass cannon. Huge upside in risk-on, destroyed by rate hikes.',
    chain: 'All-in on growth → Rate hikes crush valuations → Risk-off triggers margin calls',
    art: '🎯',
    keywords: [],
  },
  {
    id: 'eq_short',
    name: 'Short Seller',
    desk: 'equities',
    type: 'position',
    lane: 'equities',
    basePnL: -2,
    cost: 1,
    sensitivities: { risk: -3 },
    description: 'Profits from fear. Negative base P&L but thrives in crisis.',
    chain: 'Short positions gain as markets fall → Panic selling accelerates → Fear feeds more fear',
    art: '🐻',
    keywords: ['short'],
  },
  {
    id: 'eq_gme',
    name: 'GameStop Squeeze',
    desk: 'equities',
    type: 'catalyst',
    lane: 'equities',
    basePnL: 0,
    cost: 3,
    indicatorChanges: { risk: 3 },
    description: 'Retail army squeezes shorts. Destroys all Short-tagged cards.',
    chain: 'Reddit mob piles in → Short sellers squeezed → Forced buying → Risk appetite surges',
    art: '🚀',
    keywords: [],
    directEffect: 'destroy_shorts',
  },
  {
    id: 'eq_lehman',
    name: 'Lehman Brothers',
    desk: 'equities',
    type: 'position',
    lane: 'equities',
    basePnL: 8,
    cost: 4,
    sensitivities: { rate: -2, risk: 2 },
    description: 'High P&L but systemic risk. If destroyed: Risk Appetite −2.',
    chain: 'Lehman collapses → Counterparty risk explodes → Credit markets freeze → Contagion spreads',
    art: '🏚️',
    keywords: [],
    quarterEndEffect: 'destroy_40',
  },
  {
    id: 'eq_buyback',
    name: 'Share Buyback',
    desk: 'equities',
    type: 'catalyst',
    lane: 'equities',
    basePnL: 0,
    cost: 3,
    description: 'Companies buy back their own stock. All Equities positions +2. Opponent capital −2.',
    chain: 'Excess cash returned to shareholders → Share count drops → EPS rises → Capital leaves the market',
    art: '💰',
    keywords: [],
    directEffect: 'buyback',
  },
  {
    id: 'eq_momentum',
    name: 'Momentum Trade',
    desk: 'equities',
    type: 'position',
    lane: 'equities',
    basePnL: 3,
    cost: 2,
    sensitivities: { risk: 3 },
    description: 'Rides the trend. Grows +2/turn in risk-on but crashes to 0 P&L if Risk ≤ 2.',
    chain: 'Price action attracts followers → Momentum builds → Works until it doesn\'t',
    art: '📊',
    keywords: [],
    turnEffect: 'momentum',
  },
  {
    id: 'eq_activist',
    name: 'Activist Investor',
    desk: 'equities',
    type: 'position',
    lane: 'equities',
    basePnL: 5,
    cost: 3,
    sensitivities: { risk: 1 },
    description: 'Deploy: boost 1 other friendly Equities position +3.',
    chain: 'Activist takes stake → Demands changes → Unlocks value → Share price re-rates',
    art: '📢',
    keywords: [],
    directEffect: 'boost_equities_3',
  },
  {
    id: 'eq_dividend',
    name: 'Dividend Aristocrat',
    desk: 'equities',
    type: 'position',
    lane: 'equities',
    basePnL: 4,
    cost: 2,
    sensitivities: { rate: -1, risk: 1 },
    description: 'Steady income. Generates +1 capital per turn for the owner.',
    chain: 'Consistent dividend payments → Income investors pile in → Defensive in downturns',
    art: '💵',
    keywords: ['stable'],
    turnEffect: 'dividend',
  },
  {
    id: 'eq_blackmonday',
    name: 'Black Monday',
    desk: 'equities',
    type: 'catalyst',
    lane: 'equities',
    basePnL: 0,
    cost: 3,
    indicatorChanges: { risk: -5 },
    description: 'Circuit breakers triggered. Markets crash.',
    chain: 'Selling cascade → Circuit breakers halt trading → Panic spreads globally → Risk appetite evaporates',
    art: '⬛',
    keywords: ['crisis'],
  },
  {
    id: 'eq_pe',
    name: 'Private Equity',
    desk: 'equities',
    type: 'position',
    lane: 'equities',
    basePnL: 8,
    cost: 4,
    sensitivities: { rate: -3, risk: 2 },
    regimeEffects: [{
      condition: { indicator: 'rate', op: '>=', value: 7 },
      label: 'LBO Collapse',
      pnlModifier: -8,
      description: 'Can\'t refinance debt at these rates — leveraged buyouts implode.',
    }],
    description: 'Illiquid leveraged buyouts. Thrives on cheap debt. Immune to catalysts.',
    chain: 'Cheap debt fuels acquisitions → Financial engineering boosts returns → Rate hikes make refinancing impossible',
    art: '🏦',
    keywords: ['immunity'],
    turnEffect: 'growth_1',
  },
  {
    id: 'eq_crypto',
    name: 'Crypto / Bitcoin',
    desk: 'equities',
    type: 'position',
    lane: 'equities',
    basePnL: 1,
    cost: 1,
    sensitivities: { risk: 4, rate: -2 },
    description: 'Pure speculation. No fundamentals. Extreme risk sensitivity.',
    chain: 'Risk-on fuels speculation → Leverage amplifies gains → Risk-off triggers cascading liquidations',
    art: '₿',
    keywords: [],
    turnEffect: 'momentum',
  },
  {
    id: 'eq_put',
    name: 'Put Option',
    desk: 'equities',
    type: 'position',
    lane: 'equities',
    basePnL: -2,
    cost: 2,
    sensitivities: { risk: -3, rate: 1 },
    description: 'Downside protection. Costs money to hold but profits massively in a crash.',
    chain: 'Buy puts as insurance → Pay premium each period → Market crashes → Options pay off multiples',
    art: '🛡️📉',
    keywords: ['short'],
  },
  {
    id: 'eq_index',
    name: 'Index Fund',
    desk: 'equities',
    type: 'position',
    lane: 'equities',
    basePnL: 3,
    cost: 1,
    sensitivities: { risk: 2 },
    description: 'Passive market exposure. Cheap beta. The Vanguard revolution.',
    chain: 'Buy the whole market → No stock picking → Low fees → Returns match the index → Most active managers underperform',
    art: '📈',
    keywords: ['stable'],
  },
  {
    id: 'eq_vc',
    name: 'Venture Capital',
    desk: 'equities',
    type: 'position',
    lane: 'equities',
    basePnL: 0,
    cost: 3,
    sensitivities: { risk: 4, rate: -2 },
    regimeEffects: [{
      condition: { indicator: 'risk', op: '<=', value: 2 },
      label: 'Funding Winter',
      pnlModifier: -5,
      description: 'No one funds pre-revenue startups in a downturn.',
    }],
    description: 'Pre-revenue bets. Grows +3/turn in risk-on. Destroyed if risk crashes. Immune to catalysts.',
    chain: 'Easy money funds moonshots → Valuations detach from reality → Rate hikes end the party → Only survivors matter',
    art: '🚀',
    keywords: ['immunity'],
    turnEffect: 'growth_3',
  },
];

// ─── Commodities Desk (10 cards) ─────────────────────────────

const COMMODITIES_CARDS: CardDef[] = [
  {
    id: 'comm_gold',
    name: 'Gold Position',
    desk: 'commodities',
    type: 'position',
    lane: 'commodities',
    basePnL: 4,
    cost: 2,
    sensitivities: { inflation: 2, usd: -2, risk: -1 },
    regimeEffects: [{
      condition: { indicator: 'inflation', op: '>=', value: 8 },
      label: 'Inflation Hedge Activates',
      pnlModifier: 4,
      description: 'Gold thrives as a store of value in high-inflation regimes.',
    }],
    description: 'Classic safe haven. Gains from inflation, loses to strong dollar.',
    chain: 'Inflation erodes fiat value → Gold preserves purchasing power → Strong dollar makes gold expensive abroad',
    art: '🥇',
    keywords: ['safe-haven'],
  },
  {
    id: 'comm_oil',
    name: 'Oil Long',
    desk: 'commodities',
    type: 'position',
    lane: 'commodities',
    basePnL: 5,
    cost: 3,
    sensitivities: { inflation: 2, risk: 1 },
    description: 'Long crude oil. Benefits from inflation and growth.',
    chain: 'Oil demand rises with growth → Supply constraints push prices → Oil is priced in dollars',
    art: '⛽',
    keywords: [],
  },
  {
    id: 'comm_copper',
    name: 'Copper Long',
    desk: 'commodities',
    type: 'position',
    lane: 'commodities',
    basePnL: 4,
    cost: 2,
    sensitivities: { risk: 2, inflation: 1 },
    description: 'Dr. Copper reads the economy. Gains from growth and inflation.',
    chain: 'Economic growth drives construction → Copper demand rises → "Dr. Copper" signals expansion',
    art: '🔶',
    keywords: [],
  },
  {
    id: 'comm_supercycle',
    name: 'Commodity Supercycle',
    desk: 'commodities',
    type: 'position',
    lane: 'commodities',
    basePnL: 3,
    cost: 2,
    sensitivities: { inflation: 1 },
    description: 'Multi-year bull run. Grows +2/turn. The longer it stays, the stronger it gets.',
    chain: 'Underinvestment meets rising demand → Commodities enter secular bull market → Inflation ratchets higher',
    art: '📈',
    keywords: [],
    turnEffect: 'growth_2',
  },
  {
    id: 'comm_opec',
    name: 'OPEC Supply Cut',
    desk: 'commodities',
    type: 'catalyst',
    lane: 'commodities',
    basePnL: 0,
    cost: 3,
    indicatorChanges: { inflation: 3 },
    description: 'Coordinated production cut. Inflation +3. All Commodities positions +2.',
    chain: 'OPEC cuts production → Oil supply drops → Energy prices spike → Commodity positions surge',
    art: '🛢️',
    keywords: ['geopolitical'],
    directEffect: 'commodities_boost_2',
  },
  {
    id: 'comm_energy_crisis',
    name: 'Energy Crisis',
    desk: 'commodities',
    type: 'catalyst',
    lane: 'commodities',
    basePnL: 0,
    cost: 3,
    indicatorChanges: { inflation: 3, risk: -3 },
    description: 'Energy supply collapses. Stagflation: inflation spikes while risk crashes.',
    chain: 'Gas supply weaponized → Industry costs soar → Growth stalls but prices surge → Stagflation',
    art: '⚡',
    keywords: ['geopolitical', 'crisis'],
  },
  {
    id: 'comm_strategic_reserve',
    name: 'Strategic Reserve Release',
    desk: 'commodities',
    type: 'quickplay',
    lane: 'commodities',
    basePnL: 0,
    cost: 2,
    indicatorChanges: { inflation: -2 },
    description: 'Government dumps reserves. Inflation −2. Counters supply shocks.',
    chain: 'Strategic reserves tapped → Short-term supply relief → Prices drop temporarily → Political tool',
    art: '🏛️',
    keywords: [],
  },
  {
    id: 'comm_mbs',
    name: 'Mortgage-Backed Securities',
    desk: 'commodities',
    type: 'position',
    lane: 'commodities',
    basePnL: 7,
    cost: 4,
    sensitivities: { inflation: 1, rate: -2 },
    indicatorChanges: { inflation: 2 },
    regimeEffects: [{
      condition: { indicator: 'rate', op: '>=', value: 7 },
      label: 'Housing Crash',
      pnlModifier: -6,
      description: 'High rates crush mortgage demand — housing market freezes.',
    }],
    description: 'Deploy: Inflation +2. High P&L but crushed by rate hikes (housing crash).',
    chain: 'Housing demand fuels credit → Asset prices rise → Rate hikes pop the bubble',
    art: '🏠',
    keywords: [],
  },
  {
    id: 'comm_surplus',
    name: 'Trade Surplus',
    desk: 'commodities',
    type: 'position',
    lane: 'commodities',
    basePnL: 5,
    cost: 3,
    sensitivities: { usd: -2 },
    description: 'Export-driven. Benefits from weak dollar. Gains +1 capital/turn.',
    chain: 'Weak dollar makes exports competitive → Trade surplus widens → Commodity exporters profit',
    art: '🚢',
    keywords: ['em'],
    turnEffect: 'dividend',
  },
  {
    id: 'comm_green',
    name: 'Green Transition',
    desk: 'commodities',
    type: 'catalyst',
    lane: 'commodities',
    basePnL: 0,
    cost: 2,
    indicatorChanges: { inflation: 2 },
    laggedIndicatorChanges: { inflation: 2 },
    description: 'Critical minerals boom. Inflation +2 now, +2 more next turn. All Commodities positions +2.',
    chain: 'Green mandate → Lithium, cobalt demand surges → Mining can\'t keep up → Inflation compounds',
    art: '🌱',
    keywords: [],
    directEffect: 'commodities_boost_2',
  },
  {
    id: 'comm_agri',
    name: 'Agricultural Commodity',
    desk: 'commodities',
    type: 'position',
    lane: 'commodities',
    basePnL: 3,
    cost: 2,
    sensitivities: { inflation: 2, usd: -1 },
    description: 'Food prices. Inflation-linked. Weak dollar boosts exports.',
    chain: 'Crop failures and supply shocks → Food prices surge → Emerging markets hit hardest',
    art: '🌾',
    keywords: [],
  },
  {
    id: 'comm_uranium',
    name: 'Uranium Long',
    desk: 'commodities',
    type: 'position',
    lane: 'commodities',
    basePnL: 2,
    cost: 1,
    sensitivities: { inflation: 1, risk: 1 },
    description: 'Nuclear energy play. Long-cycle. Grows +2/turn.',
    chain: 'Energy transition drives nuclear demand → Supply-constrained market → Secular bull case builds',
    art: '☢️',
    keywords: [],
    turnEffect: 'growth_2',
  },
  {
    id: 'comm_short_oil',
    name: 'Short Oil',
    desk: 'commodities',
    type: 'position',
    lane: 'commodities',
    basePnL: -1,
    cost: 1,
    sensitivities: { inflation: -2, risk: -1 },
    description: 'Bet against oil. Profits from deflation and demand destruction.',
    chain: 'Short crude futures → Recession kills demand → Oil crashes → Deflation narrative builds',
    art: '🛢️📉',
    keywords: ['short'],
  },
];

// ─── FX Desk (10 cards) ──────────────────────────────────────

const FX_CARDS: CardDef[] = [
  {
    id: 'fx_soros',
    name: 'George Soros',
    desk: 'fx',
    type: 'position',
    lane: 'fx',
    basePnL: 7,
    cost: 4,
    sensitivities: { usd: -2 },
    indicatorChanges: { usd: -3 },
    description: 'Break the central bank. Deploy: USD −3.',
    chain: 'Soros sells the pound → Central bank defenses crumble → Currency collapses → Dollar weakens in sympathy',
    art: '🦅',
    keywords: [],
  },
  {
    id: 'fx_carry',
    name: 'Carry Trade',
    desk: 'fx',
    type: 'position',
    lane: 'fx',
    basePnL: 3,
    cost: 2,
    sensitivities: { rate: 2, risk: 2 },
    regimeEffects: [{
      condition: { indicator: 'risk', op: '<=', value: 3 },
      label: 'Carry Unwind',
      pnlModifier: -5,
      description: 'Risk-off triggers violent carry trade liquidation.',
    }],
    description: 'Borrow low, lend high. Unwinds violently in risk-off.',
    chain: 'Rate differential drives carry income → Risk-off triggers unwind → Positions liquidated in panic',
    art: '💱',
    keywords: [],
  },
  {
    id: 'fx_wrecking',
    name: 'Dollar Wrecking Ball',
    desk: 'fx',
    type: 'catalyst',
    lane: 'fx',
    basePnL: 0,
    cost: 3,
    indicatorChanges: { usd: 3 },
    description: 'King dollar crushes everything.',
    chain: 'Fed hikes → Capital flows to US → Dollar strengthens → EM debt burden explodes → Global tightening',
    art: '💪',
    keywords: [],
  },
  {
    id: 'fx_plaza',
    name: 'Plaza Accord',
    desk: 'fx',
    type: 'catalyst',
    lane: 'fx',
    basePnL: 0,
    cost: 3,
    indicatorChanges: { usd: -3 },
    description: 'Coordinated intervention to weaken the dollar.',
    chain: 'G5 nations agree to weaken dollar → Coordinated selling → Dollar falls → Trade imbalances correct',
    art: '🤝',
    keywords: ['historical'],
  },
  {
    id: 'fx_emcrisis',
    name: 'EM Currency Crisis',
    desk: 'fx',
    type: 'catalyst',
    lane: 'fx',
    basePnL: 0,
    cost: 2,
    indicatorChanges: { usd: 2, risk: -2 },
    description: 'Capital flight from developing economies.',
    chain: 'EM currencies collapse → Capital flees to safety → Dollar strengthens → Contagion spreads',
    art: '🌍',
    keywords: ['em'],
  },
  {
    id: 'fx_tariffs',
    name: 'Trump Tariffs',
    desk: 'fx',
    type: 'catalyst',
    lane: 'fx',
    basePnL: 0,
    cost: 3,
    indicatorChanges: { usd: 2, inflation: 2, risk: -2 },
    description: 'Trade wars are easy to win.',
    chain: 'Tariffs imposed → Import prices rise → Inflation ticks up → Trade uncertainty → Risk-off',
    art: '🏷️',
    keywords: ['geopolitical'],
  },
  {
    id: 'fx_yuan',
    name: 'Yuan Devaluation',
    desk: 'fx',
    type: 'position',
    lane: 'fx',
    basePnL: 6,
    cost: 3,
    sensitivities: { usd: 2 },
    indicatorChanges: { usd: 2 },
    description: 'PBOC lets it slide. Deploy: USD +2.',
    chain: 'China devalues yuan → Competitive devaluation → Dollar strengthens relatively → Trade tensions rise',
    art: '🇨🇳',
    keywords: [],
  },
  {
    id: 'fx_swissfranc',
    name: 'Swiss Franc Peg Break',
    desk: 'fx',
    type: 'catalyst',
    lane: 'fx',
    basePnL: 0,
    cost: 2,
    indicatorChanges: { risk: -2 },
    description: 'SNB abandons the peg. FX chaos.',
    chain: 'Swiss National Bank surprises markets → Franc surges → FX positions blown out → Brokers collapse',
    art: '🇨🇭',
    keywords: [],
    directEffect: 'fx_chaos',
  },
  {
    id: 'fx_petrodollar',
    name: 'Petrodollar Recycling',
    desk: 'fx',
    type: 'position',
    lane: 'fx',
    basePnL: 4,
    cost: 2,
    sensitivities: { inflation: 1, usd: 1 },
    description: 'Oil revenue recycled into dollar assets.',
    chain: 'Oil exporters earn dollars → Recycled into US treasuries → Dollar demand sustained → System reinforced',
    art: '🏗️',
    keywords: ['stable'],
  },
  {
    id: 'fx_nixon',
    name: 'Nixon Shock',
    desk: 'fx',
    type: 'catalyst',
    lane: 'fx',
    basePnL: 0,
    cost: 2,
    indicatorChanges: { usd: -2 },
    description: 'Gold window closed. End of Bretton Woods.',
    chain: 'Nixon ends gold convertibility → Dollar floats → Uncertainty spikes → Stable positions disrupted',
    art: '🪙',
    keywords: ['historical'],
    directEffect: 'stable_minus_2',
  },
  {
    id: 'fx_em_debt',
    name: 'EM Sovereign Debt',
    desk: 'fx',
    type: 'position',
    lane: 'fx',
    basePnL: 6,
    cost: 3,
    sensitivities: { rate: 1, usd: -3, risk: 1 },
    regimeEffects: [{
      condition: { indicator: 'usd', op: '>=', value: 7 },
      label: 'EM Default Cascade',
      pnlModifier: -6,
      description: 'Strong dollar makes dollar-denominated EM debt unpayable.',
    }],
    description: 'High-yield emerging market bonds. Crushed by strong dollar.',
    chain: 'Yield seekers buy EM debt → Dollar strengthens → Debt service costs explode → Defaults cascade',
    art: '🌍',
    keywords: ['em'],
  },
  {
    id: 'fx_chf',
    name: 'Swiss Franc Position',
    desk: 'fx',
    type: 'position',
    lane: 'fx',
    basePnL: 3,
    cost: 2,
    sensitivities: { risk: -1, inflation: -1, usd: -1 },
    description: 'Safe haven currency. Strengthens in crisis, weakens in risk-on.',
    chain: 'Global uncertainty → Capital flows to Switzerland → Franc appreciates → Safe haven premium',
    art: '🇨🇭',
    keywords: ['safe-haven', 'stable'],
  },
  {
    id: 'fx_short_em',
    name: 'Short EM Currencies',
    desk: 'fx',
    type: 'position',
    lane: 'fx',
    basePnL: -1,
    cost: 1,
    sensitivities: { usd: 2, risk: -2 },
    description: 'Bet against emerging market currencies. Profits from strong dollar and crisis.',
    chain: 'Short EM FX → Dollar strengthens → Capital flees emerging markets → EM currencies collapse',
    art: '💱📉',
    keywords: ['short'],
  },
];

// ─── Macro Desk (10 cards) ───────────────────────────────────

const MACRO_CARDS: CardDef[] = [
  {
    id: 'macro_covid',
    name: 'COVID Pandemic',
    desk: 'macro',
    type: 'catalyst',
    lane: 'any',
    basePnL: 0,
    cost: 3,
    indicatorChanges: { risk: -5, inflation: -2 },
    description: 'Everything stops. Global shutdown.',
    chain: 'Pandemic declared → Lockdowns imposed → Demand collapses → Deflation fears → Markets crash',
    art: '🦠',
    keywords: ['crisis'],
  },
  {
    id: 'macro_stimulus',
    name: 'COVID Stimulus',
    desk: 'macro',
    type: 'catalyst',
    lane: 'any',
    basePnL: 0,
    cost: 4,
    indicatorChanges: { rate: -2, risk: 3 },
    laggedIndicatorChanges: { inflation: 4 },
    lagTurns: 4,
    description: 'The everything rally. Risk +3 now, Inflation +4 in 4 turns (stimulus inflation was deeply lagged).',
    chain: 'Trillions printed → Rates slashed → Risk assets rally → Inflation follows months later',
    art: '💸',
    keywords: ['stimulus'],
  },
  {
    id: 'macro_bretton',
    name: 'Bretton Woods',
    desk: 'macro',
    type: 'catalyst',
    lane: 'any',
    basePnL: 0,
    cost: 3,
    description: 'Reset the world order. All indicators move toward neutral.',
    chain: 'New monetary framework → Exchange rates stabilized → Global order restored → Markets reset',
    art: '🌐',
    keywords: ['historical'],
    directEffect: 'reset_indicators',
  },
  {
    id: 'macro_elon',
    name: 'Elon Musk',
    desk: 'macro',
    type: 'position',
    lane: 'any',
    basePnL: 5,
    cost: 3,
    description: 'Chaos incarnate. Each turn: random indicator ±1.',
    chain: 'Musk tweets → Markets react → Nobody knows what\'s next → Volatility is the only certainty',
    art: '🚀',
    keywords: [],
    turnEffect: 'random_indicator',
  },
  {
    id: 'macro_sbf',
    name: 'SBF',
    desk: 'macro',
    type: 'position',
    lane: 'any',
    basePnL: 11,
    cost: 4,
    description: 'Huge P&L but 70% chance of destruction at quarter end. If destroyed: Risk −1.',
    chain: 'Leveraged empire built on sand → House of cards → Fraud revealed → Contagion spreads',
    art: '🃏',
    keywords: [],
    quarterEndEffect: 'destroy_70_risk',
  },
  {
    id: 'macro_war',
    name: 'War Economy',
    desk: 'macro',
    type: 'position',
    lane: 'any',
    basePnL: 3,
    cost: 2,
    sensitivities: {},
    description: 'Military spending boost. Grows +3/turn. If Inflation hits 5, destroyed.',
    chain: 'Defense spending surges → GDP boosted → But inflation overheats → Guns vs butter tradeoff',
    art: '⚔️',
    keywords: ['war'],
    turnEffect: 'growth_3',
  },
  {
    id: 'macro_regime',
    name: 'Regime Change',
    desk: 'macro',
    type: 'catalyst',
    lane: 'any',
    basePnL: 0,
    cost: 2,
    description: 'New paradigm. Swap Interest Rate and Inflation values.',
    chain: 'Policy regime shifts → Old correlations break → Markets reprice everything → New normal emerges',
    art: '🔄',
    keywords: [],
    directEffect: 'swap_rate_inflation',
  },
  {
    id: 'macro_sanctions',
    name: 'Sanctions',
    desk: 'macro',
    type: 'catalyst',
    lane: 'any',
    basePnL: 0,
    cost: 2,
    indicatorChanges: { usd: 2 },
    description: 'Freeze 1 opponent position for 2 turns. USD +2.',
    chain: 'Economic sanctions imposed → Assets frozen → Dollar demand spikes → Target isolated from markets',
    art: '🚫',
    keywords: ['geopolitical'],
    directEffect: 'freeze_opponent',
  },
  {
    id: 'macro_blackswan',
    name: 'Black Swan',
    desk: 'macro',
    type: 'position',
    lane: 'any',
    basePnL: 0,
    cost: 1,
    sensitivities: { risk: -4 },
    description: 'Tail risk bet. Massive profit from crisis, worthless otherwise.',
    chain: 'Out-of-the-money puts → Market crashes → Convexity kicks in → Asymmetric payoff',
    art: '🦢',
    keywords: [],
  },
  {
    id: 'macro_trump_tweet',
    name: 'Trump Tweet',
    desk: 'macro',
    type: 'catalyst',
    lane: 'any',
    basePnL: 0,
    cost: 1,
    description: 'Truth Social, 3am. Random indicator ±2.',
    chain: 'Presidential tweet → Markets scramble to interpret → Algorithms react → Volatility spikes',
    art: '📱',
    keywords: ['chaos'],
    directEffect: 'random_indicator_2',
  },
  {
    id: 'macro_cds',
    name: 'CDS',
    desk: 'macro',
    type: 'position',
    lane: 'any',
    basePnL: -1,
    cost: 2,
    sensitivities: { risk: -3, rate: 1 },
    regimeEffects: [{
      condition: { indicator: 'risk', op: '<=', value: 2 },
      label: 'Credit Event',
      pnlModifier: 8,
      description: 'Default triggers CDS payout — massive profit from crisis insurance.',
    }],
    description: 'Credit default swap. Costs money to hold but pays off enormously in crisis.',
    chain: 'Pay premium each period → Wait for credit event → Default triggers payout → Insurance pays off',
    art: '🛡️',
    keywords: [],
  },
  {
    id: 'macro_vix',
    name: 'VIX Long',
    desk: 'macro',
    type: 'position',
    lane: 'any',
    basePnL: -1,
    cost: 1,
    sensitivities: { risk: -4 },
    description: 'Volatility bet. Bleeds in calm markets, spikes in crisis. Convex payoff.',
    chain: 'Volatility decays in calm markets → Crisis hits → VIX spikes → Convex payout rewards patience',
    art: '📊',
    keywords: [],
  },
  {
    id: 'macro_distressed',
    name: 'Distressed Debt',
    desk: 'macro',
    type: 'position',
    lane: 'any',
    basePnL: 0,
    cost: 2,
    sensitivities: { risk: -2, rate: -1 },
    regimeEffects: [{
      condition: { indicator: 'risk', op: '<=', value: 2 },
      label: 'Vulture Profit',
      pnlModifier: 6,
      description: 'Buying debt at pennies on the dollar. Crisis is opportunity for vulture funds.',
    }],
    description: 'Buy bankruptcies for pennies. Profits from crisis and rate cuts.',
    chain: 'Companies default → Debt trades at 20¢ on the dollar → Vulture funds buy → Recovery returns multiples',
    art: '🦅',
    keywords: [],
  },
  {
    id: 'macro_margin_tightening',
    name: 'Margin Tightening',
    desk: 'macro',
    type: 'catalyst',
    lane: 'any',
    basePnL: 0,
    cost: 3,
    indicatorChanges: { risk: -2 },
    description: 'Brokers raise margin requirements. Risk −2. Forces overleveraged players to deleverage.',
    chain: 'Regulators tighten margin rules → Brokers pass it through → Leveraged positions get squeezed → Forced selling',
    art: '📋',
    keywords: [],
    directEffect: 'margin_tightening',
  },
  {
    id: 'macro_funding_freeze',
    name: 'Funding Freeze',
    desk: 'macro',
    type: 'trap',
    lane: 'any',
    basePnL: 0,
    cost: 2,
    description: 'When Risk ≤ 2: all carrying costs doubled this turn. Credit markets seize.',
    chain: 'Counterparty fear spikes → Interbank lending stops → LIBOR-OIS blows out → Nobody can fund',
    art: '🧊',
    keywords: ['trap'],
    trapCondition: { type: 'indicator_below', indicator: 'risk', threshold: 2 },
    directEffect: 'funding_freeze',
  },
];

// ─── Trap Cards ──────────────────────────────────────────────
// Set face-down. Auto-trigger when the macro condition is met.
// These are the "Recall the Debt" plays — engineer the market, spring the trap.

const TRAP_CARDS: CardDef[] = [
  {
    id: 'trap_margin_call',
    name: 'Margin Call',
    desk: 'macro',
    type: 'trap',
    lane: 'any',
    basePnL: 0,
    cost: 2,
    description: 'When Rate ≥ 6: destroy all opponent positions with negative rate sensitivity.',
    chain: 'Rates rise → Leveraged players can\'t service debt → Forced liquidation → Positions wiped',
    art: '📞',
    keywords: ['trap'],
    trapCondition: { type: 'indicator_above', indicator: 'rate', threshold: 6 },
    directEffect: 'trap_destroy_neg_rate_sens',
  },
  {
    id: 'trap_short_squeeze',
    name: 'Short Squeeze',
    desk: 'macro',
    type: 'trap',
    lane: 'any',
    basePnL: 0,
    cost: 2,
    description: 'When Risk ≥ 8: destroy all opponent equity lane positions.',
    chain: 'Euphoria peaks → Overleveraged longs get margin called → Equity positions wiped in the squeeze',
    art: '🐻🔥',
    keywords: ['trap'],
    trapCondition: { type: 'indicator_above', indicator: 'risk', threshold: 8 },
    directEffect: 'trap_destroy_opponent_shorts',
  },
  {
    id: 'trap_sovereign_debt',
    name: 'Sovereign Debt Crisis',
    desk: 'macro',
    type: 'trap',
    lane: 'any',
    basePnL: 0,
    cost: 2,
    description: 'When USD ≥ 7: destroy opponent\'s 2 highest P&L positions.',
    chain: 'Dollar surges → EM debt becomes unpayable → Defaults cascade → Contagion hits the strongest first',
    art: '🏛️💀',
    keywords: ['trap', 'geopolitical'],
    trapCondition: { type: 'indicator_above', indicator: 'usd', threshold: 7 },
    directEffect: 'trap_destroy_top_2',
  },
  {
    id: 'trap_panic_selling',
    name: 'Panic Selling',
    desk: 'macro',
    type: 'trap',
    lane: 'any',
    basePnL: 0,
    cost: 1,
    description: 'When Risk ≤ 2: all opponent board positions −3 P&L.',
    chain: 'Fear grips the market → Indiscriminate selling → Everything goes → No bids anywhere',
    art: '😱',
    keywords: ['trap', 'crisis'],
    trapCondition: { type: 'indicator_below', indicator: 'risk', threshold: 2 },
    directEffect: 'trap_opponent_minus_3',
  },
  {
    id: 'trap_recall_debt',
    name: 'Recall the Debt',
    desk: 'macro',
    type: 'trap',
    lane: 'any',
    basePnL: 0,
    cost: 1,
    description: 'When opponent deploys a position: it enters −3 P&L (debt recalled on arrival).',
    chain: 'Easy money creates overcapacity → Creditors pull credit lines → Position enters underwater',
    art: '🪤',
    keywords: ['trap'],
    trapCondition: { type: 'opponent_plays_position' },
    directEffect: 'trap_debuff_entry',
  },
];

// ─── Export ──────────────────────────────────────────────────

export const ALL_CARDS: CardDef[] = [
  ...RATES_CARDS,
  ...EQUITIES_CARDS,
  ...COMMODITIES_CARDS,
  ...FX_CARDS,
  ...MACRO_CARDS,
  ...TRAP_CARDS,
];

export const CARD_MAP: Record<string, CardDef> = Object.fromEntries(
  ALL_CARDS.map(c => [c.id, c])
);

export function getCardsForDesk(desk: string): CardDef[] {
  return ALL_CARDS.filter(c => c.desk === desk);
}
