// ═══════════════════════════════════════════════════════════════
//  MACRO v2 — Card Definitions
//  50 cards across 5 Trading Desks. Each card has real-world
//  transmission logic baked into its sensitivities and effects.
// ═══════════════════════════════════════════════════════════════

import { CardDef } from './types';

// ─── Rates Desk (10 cards) ───────────────────────────────────

const RATES_CARDS: CardDef[] = [
  {
    id: 'rates_powell',
    name: 'Jerome Powell',
    desk: 'rates',
    type: 'position',
    lane: 'rates',
    basePnL: 6,
    sensitivities: { rate: 3, risk: -1 },
    indicatorChanges: { rate: -1 },
    description: 'Fed Chair. Deploy: Rate −1. Strong rate sensitivity.',
    chain: 'Powell speaks → Markets price in dovish pivot → Rates fall',
    art: '🏛️',
    keywords: ['fed', 'official'],
  },
  {
    id: 'rates_volcker',
    name: 'Paul Volcker',
    desk: 'rates',
    type: 'catalyst',
    lane: 'rates',
    basePnL: 0,
    indicatorChanges: { rate: 2, inflation: -1 },
    description: 'Volcker shock: crush inflation at any cost.',
    chain: 'Volcker hikes aggressively → Rates spike → Inflation expectations break → Economy slows',
    art: '🔨',
    keywords: ['fed', 'historical'],
  },
  {
    id: 'rates_yci',
    name: 'Yield Curve Inversion',
    desk: 'rates',
    type: 'catalyst',
    lane: 'rates',
    basePnL: 0,
    indicatorChanges: { risk: -2 },
    description: 'Inverted curve signals recession ahead.',
    chain: 'Short rates exceed long rates → Recession signal flashes → Risk appetite collapses',
    art: '📉',
    keywords: ['signal'],
  },
  {
    id: 'rates_qe',
    name: 'QE Infinity',
    desk: 'rates',
    type: 'catalyst',
    lane: 'rates',
    basePnL: 0,
    indicatorChanges: { rate: -1, risk: 2 },
    description: 'Money printer goes brrr.',
    chain: 'Fed buys everything → Rates pinned at zero → Liquidity floods markets → Risk assets rally',
    art: '🖨️',
    keywords: ['fed', 'stimulus'],
  },
  {
    id: 'rates_10y',
    name: '10-Year Treasury',
    desk: 'rates',
    type: 'position',
    lane: 'rates',
    basePnL: 4,
    sensitivities: { rate: 2, inflation: -1, risk: -1 },
    description: 'Benchmark bond. Gains from rate hikes, loses to inflation.',
    chain: 'Treasury yields move with policy rates → Inflation erodes real returns → Safe haven in risk-off',
    art: '📜',
    keywords: ['bond', 'stable'],
  },
  {
    id: 'rates_tips',
    name: 'TIPS Position',
    desk: 'rates',
    type: 'position',
    lane: 'rates',
    basePnL: 3,
    sensitivities: { inflation: 2, rate: 1 },
    description: 'Treasury Inflation-Protected Securities. Hedges inflation.',
    chain: 'Inflation rises → TIPS principal adjusts upward → Real yield preserved',
    art: '🛡️',
    keywords: ['bond', 'inflation-linked'],
  },
  {
    id: 'rates_yellen',
    name: 'Janet Yellen',
    desk: 'rates',
    type: 'position',
    lane: 'rates',
    basePnL: 5,
    sensitivities: { rate: 2, usd: 1 },
    indicatorChanges: { usd: 1 },
    description: 'Treasury Secretary. Deploy: USD +1. Benefits from strong dollar policy.',
    chain: 'Yellen signals strong dollar → USD strengthens → Treasury demand rises',
    art: '🏦',
    keywords: ['official'],
  },
  {
    id: 'rates_bailout',
    name: '2008 Bailout',
    desk: 'rates',
    type: 'catalyst',
    lane: 'rates',
    basePnL: 0,
    indicatorChanges: { rate: -2, risk: 1 },
    description: 'Too big to fail. Emergency rate cuts.',
    chain: 'Banks rescued → Fed slashes rates to zero → Confidence partially restored → TARP stabilizes system',
    art: '💰',
    keywords: ['crisis', 'historical'],
  },
  {
    id: 'rates_repo',
    name: 'Repo Market Stress',
    desk: 'rates',
    type: 'catalyst',
    lane: 'rates',
    basePnL: 0,
    indicatorChanges: { risk: -1 },
    description: 'Plumbing breaks. Overnight funding markets seize.',
    chain: 'Repo rates spike → Banks hoard cash → Fed forced to intervene → Systemic risk flares',
    art: '🔧',
    keywords: ['crisis'],
  },
  {
    id: 'rates_duration',
    name: 'Duration Play',
    desk: 'rates',
    type: 'position',
    lane: 'rates',
    basePnL: 2,
    sensitivities: { rate: 4, inflation: -2 },
    description: 'High-conviction long-duration bet. Massive rate sensitivity.',
    chain: 'Long-dated bonds move violently with rate expectations → Inflation is the enemy of duration',
    art: '📏',
    keywords: ['bond'],
  },
];

// ─── Equities Desk (10 cards) ────────────────────────────────

const EQUITIES_CARDS: CardDef[] = [
  {
    id: 'eq_buffett',
    name: 'Warren Buffett',
    desk: 'equities',
    type: 'position',
    lane: 'equities',
    basePnL: 5,
    sensitivities: { risk: 1 },
    description: 'Oracle of Omaha. Immune to catalysts. Grows +1/turn.',
    chain: 'Value investing compounds quietly → Buffett sits through volatility → Long-term gains',
    art: '🎩',
    keywords: ['immunity'],
    turnEffect: 'growth_1',
  },
  {
    id: 'eq_concentrated',
    name: 'Concentrated Bet',
    desk: 'equities',
    type: 'position',
    lane: 'equities',
    basePnL: 10,
    sensitivities: { rate: -3, risk: 3 },
    description: 'Glass cannon. Huge upside in risk-on, destroyed by rate hikes.',
    chain: 'All-in on growth → Rate hikes crush valuations → Risk-off triggers margin calls',
    art: '🎯',
    keywords: [],
  },
  {
    id: 'eq_short',
    name: 'Short Seller',
    desk: 'equities',
    type: 'position',
    lane: 'equities',
    basePnL: -2,
    sensitivities: { risk: -3 },
    description: 'Profits from fear. Negative base P&L but thrives in crisis.',
    chain: 'Short positions gain as markets fall → Panic selling accelerates → Fear feeds more fear',
    art: '🐻',
    keywords: ['short'],
  },
  {
    id: 'eq_gme',
    name: 'GameStop Squeeze',
    desk: 'equities',
    type: 'catalyst',
    lane: 'equities',
    basePnL: 0,
    indicatorChanges: { risk: 2 },
    description: 'Retail army squeezes shorts. Destroys all Short-tagged cards.',
    chain: 'Reddit mob piles in → Short sellers squeezed → Forced buying → Risk appetite surges',
    art: '🚀',
    keywords: [],
    directEffect: 'destroy_shorts',
  },
  {
    id: 'eq_lehman',
    name: 'Lehman Brothers',
    desk: 'equities',
    type: 'position',
    lane: 'equities',
    basePnL: 8,
    sensitivities: { rate: -2, risk: 2 },
    description: 'High P&L but systemic risk. If destroyed: Risk Appetite −2.',
    chain: 'Lehman collapses → Counterparty risk explodes → Credit markets freeze → Contagion spreads',
    art: '🏚️',
    keywords: [],
    quarterEndEffect: 'destroy_40',
  },
  {
    id: 'eq_earnings',
    name: 'Earnings Season',
    desk: 'equities',
    type: 'catalyst',
    lane: 'equities',
    basePnL: 0,
    description: 'Beat expectations across the board. All Equities positions +2.',
    chain: 'Companies report strong earnings → Analysts revise up → Equity multiples expand',
    art: '📊',
    keywords: [],
    directEffect: 'equities_boost_2',
  },
  {
    id: 'eq_techbubble',
    name: 'Tech Bubble',
    desk: 'equities',
    type: 'position',
    lane: 'equities',
    basePnL: 12,
    sensitivities: { rate: -4, risk: 3 },
    description: 'Massive P&L but fragile. 40% chance of being destroyed at quarter end.',
    chain: 'Valuations detach from reality → Rate hikes pop the bubble → Greed sustains it until it doesn\'t',
    art: '🫧',
    keywords: [],
    quarterEndEffect: 'destroy_40',
  },
  {
    id: 'eq_activist',
    name: 'Activist Investor',
    desk: 'equities',
    type: 'position',
    lane: 'equities',
    basePnL: 5,
    sensitivities: { risk: 1 },
    description: 'Deploy: boost 1 other friendly Equities position +3.',
    chain: 'Activist takes stake → Demands changes → Unlocks value → Share price re-rates',
    art: '📢',
    keywords: [],
    directEffect: 'boost_equities_3',
  },
  {
    id: 'eq_ipo',
    name: 'IPO Frenzy',
    desk: 'equities',
    type: 'catalyst',
    lane: 'equities',
    basePnL: 0,
    indicatorChanges: { risk: 1 },
    description: 'Hot IPO market. All Equities positions +1.',
    chain: 'New listings flood the market → Investors chase growth → Animal spirits run high',
    art: '🔔',
    keywords: [],
    directEffect: 'equities_boost_1',
  },
  {
    id: 'eq_blackmonday',
    name: 'Black Monday',
    desk: 'equities',
    type: 'catalyst',
    lane: 'equities',
    basePnL: 0,
    indicatorChanges: { risk: -3 },
    description: 'Circuit breakers triggered. Markets crash.',
    chain: 'Selling cascade → Circuit breakers halt trading → Panic spreads globally → Risk appetite evaporates',
    art: '⬛',
    keywords: ['crisis'],
  },
];

// ─── Commodities Desk (10 cards) ─────────────────────────────

const COMMODITIES_CARDS: CardDef[] = [
  {
    id: 'comm_opec',
    name: 'OPEC Embargo',
    desk: 'commodities',
    type: 'catalyst',
    lane: 'commodities',
    basePnL: 0,
    indicatorChanges: { inflation: 2 },
    description: 'Supply squeezed. Oil soars.',
    chain: 'OPEC cuts production → Oil supply drops → Energy prices spike → Inflation surges across the economy',
    art: '🛢️',
    keywords: ['geopolitical'],
  },
  {
    id: 'comm_gold',
    name: 'Gold Position',
    desk: 'commodities',
    type: 'position',
    lane: 'commodities',
    basePnL: 4,
    sensitivities: { inflation: 2, usd: -2, risk: -1 },
    description: 'Classic safe haven. Gains from inflation, loses to strong dollar.',
    chain: 'Inflation erodes fiat value → Gold preserves purchasing power → Strong dollar makes gold expensive abroad',
    art: '🥇',
    keywords: ['safe-haven'],
  },
  {
    id: 'comm_oil',
    name: 'Oil Long',
    desk: 'commodities',
    type: 'position',
    lane: 'commodities',
    basePnL: 5,
    sensitivities: { inflation: 2, risk: 1 },
    description: 'Long crude oil. Benefits from inflation and growth.',
    chain: 'Oil demand rises with growth → Supply constraints push prices → Oil is priced in dollars',
    art: '⛽',
    keywords: [],
  },
  {
    id: 'comm_mbs',
    name: 'Mortgage-Backed Securities',
    desk: 'commodities',
    type: 'position',
    lane: 'commodities',
    basePnL: 7,
    sensitivities: { inflation: 1 },
    indicatorChanges: { inflation: 1 },
    description: 'Deploy: Inflation +1. Housing-linked asset.',
    chain: 'Housing demand fuels credit expansion → Asset prices rise → Inflation pressure builds',
    art: '🏠',
    keywords: [],
  },
  {
    id: 'comm_putin',
    name: 'Putin Gas Cutoff',
    desk: 'commodities',
    type: 'catalyst',
    lane: 'commodities',
    basePnL: 0,
    indicatorChanges: { inflation: 2, risk: -1 },
    description: 'Europe scrambles for energy.',
    chain: 'Russia weaponizes gas → European energy crisis → Industry costs soar → Stagflation fears grip markets',
    art: '🇷🇺',
    keywords: ['geopolitical'],
  },
  {
    id: 'comm_iran',
    name: 'Iran Conflict',
    desk: 'commodities',
    type: 'catalyst',
    lane: 'commodities',
    basePnL: 0,
    indicatorChanges: { inflation: 1, risk: -2 },
    description: 'Strait of Hormuz at risk. Oil supply threatened.',
    chain: 'Military escalation → Oil transit route threatened → Supply premium spikes → Global risk-off',
    art: '⚔️',
    keywords: ['geopolitical', 'war'],
  },
  {
    id: 'comm_supercycle',
    name: 'Commodity Supercycle',
    desk: 'commodities',
    type: 'position',
    lane: 'commodities',
    basePnL: 3,
    sensitivities: { inflation: 1 },
    description: 'Multi-year commodity bull run. Grows +2/turn.',
    chain: 'Underinvestment meets rising demand → Commodities enter secular bull market → Inflation ratchets higher',
    art: '📈',
    keywords: [],
    turnEffect: 'growth_2',
  },
  {
    id: 'comm_surplus',
    name: 'Trade Surplus',
    desk: 'commodities',
    type: 'position',
    lane: 'commodities',
    basePnL: 5,
    sensitivities: { usd: -2 },
    description: 'Export-driven position. Benefits from weak dollar.',
    chain: 'Weak dollar makes exports competitive → Trade surplus widens → Commodity exporters profit',
    art: '🚢',
    keywords: ['em'],
  },
  {
    id: 'comm_copper',
    name: 'Copper Long',
    desk: 'commodities',
    type: 'position',
    lane: 'commodities',
    basePnL: 4,
    sensitivities: { risk: 2, inflation: 1 },
    description: 'Dr. Copper reads the economy. Gains from growth and inflation.',
    chain: 'Economic growth drives construction → Copper demand rises → "Dr. Copper" signals expansion',
    art: '🔶',
    keywords: [],
  },
  {
    id: 'comm_green',
    name: 'Green Transition',
    desk: 'commodities',
    type: 'catalyst',
    lane: 'commodities',
    basePnL: 0,
    indicatorChanges: { inflation: 1 },
    description: 'Critical minerals boom. All Commodities positions +2.',
    chain: 'Green energy mandate → Lithium, cobalt demand surges → Mining can\'t keep up → Commodity prices spike',
    art: '🌱',
    keywords: [],
    directEffect: 'commodities_boost_2',
  },
];

// ─── FX Desk (10 cards) ──────────────────────────────────────

const FX_CARDS: CardDef[] = [
  {
    id: 'fx_soros',
    name: 'George Soros',
    desk: 'fx',
    type: 'position',
    lane: 'fx',
    basePnL: 7,
    sensitivities: { usd: -2 },
    indicatorChanges: { usd: -2 },
    description: 'Break the central bank. Deploy: USD −2.',
    chain: 'Soros sells the pound → Central bank defenses crumble → Currency collapses → Dollar weakens in sympathy',
    art: '🦅',
    keywords: [],
  },
  {
    id: 'fx_carry',
    name: 'Carry Trade',
    desk: 'fx',
    type: 'position',
    lane: 'fx',
    basePnL: 3,
    sensitivities: { rate: 2, risk: 2 },
    description: 'Borrow low, lend high. Unwinds violently in risk-off.',
    chain: 'Rate differential drives carry income → Risk-off triggers unwind → Positions liquidated in panic',
    art: '💱',
    keywords: [],
  },
  {
    id: 'fx_wrecking',
    name: 'Dollar Wrecking Ball',
    desk: 'fx',
    type: 'catalyst',
    lane: 'fx',
    basePnL: 0,
    indicatorChanges: { usd: 2 },
    description: 'King dollar crushes everything.',
    chain: 'Fed hikes → Capital flows to US → Dollar strengthens → EM debt burden explodes → Global tightening',
    art: '💪',
    keywords: [],
  },
  {
    id: 'fx_plaza',
    name: 'Plaza Accord',
    desk: 'fx',
    type: 'catalyst',
    lane: 'fx',
    basePnL: 0,
    indicatorChanges: { usd: -2 },
    description: 'Coordinated intervention to weaken the dollar.',
    chain: 'G5 nations agree to weaken dollar → Coordinated selling → Dollar falls → Trade imbalances correct',
    art: '🤝',
    keywords: ['historical'],
  },
  {
    id: 'fx_emcrisis',
    name: 'EM Currency Crisis',
    desk: 'fx',
    type: 'catalyst',
    lane: 'fx',
    basePnL: 0,
    indicatorChanges: { usd: 1, risk: -1 },
    description: 'Capital flight from developing economies.',
    chain: 'EM currencies collapse → Capital flees to safety → Dollar strengthens → Contagion spreads',
    art: '🌍',
    keywords: ['em'],
  },
  {
    id: 'fx_tariffs',
    name: 'Trump Tariffs',
    desk: 'fx',
    type: 'catalyst',
    lane: 'fx',
    basePnL: 0,
    indicatorChanges: { usd: 1, inflation: 1, risk: -1 },
    description: 'Trade wars are easy to win.',
    chain: 'Tariffs imposed → Import prices rise → Inflation ticks up → Trade uncertainty → Risk-off',
    art: '🏷️',
    keywords: ['geopolitical'],
  },
  {
    id: 'fx_yuan',
    name: 'Yuan Devaluation',
    desk: 'fx',
    type: 'position',
    lane: 'fx',
    basePnL: 6,
    sensitivities: { usd: 2 },
    indicatorChanges: { usd: 1 },
    description: 'PBOC lets it slide. Deploy: USD +1.',
    chain: 'China devalues yuan → Competitive devaluation → Dollar strengthens relatively → Trade tensions rise',
    art: '🇨🇳',
    keywords: [],
  },
  {
    id: 'fx_swissfranc',
    name: 'Swiss Franc Peg Break',
    desk: 'fx',
    type: 'catalyst',
    lane: 'fx',
    basePnL: 0,
    indicatorChanges: { risk: -1 },
    description: 'SNB abandons the peg. FX chaos.',
    chain: 'Swiss National Bank surprises markets → Franc surges → FX positions blown out → Brokers collapse',
    art: '🇨🇭',
    keywords: [],
    directEffect: 'fx_chaos',
  },
  {
    id: 'fx_petrodollar',
    name: 'Petrodollar Recycling',
    desk: 'fx',
    type: 'position',
    lane: 'fx',
    basePnL: 4,
    sensitivities: { inflation: 1, usd: 1 },
    description: 'Oil revenue recycled into dollar assets.',
    chain: 'Oil exporters earn dollars → Recycled into US treasuries → Dollar demand sustained → System reinforced',
    art: '🏗️',
    keywords: ['stable'],
  },
  {
    id: 'fx_nixon',
    name: 'Nixon Shock',
    desk: 'fx',
    type: 'catalyst',
    lane: 'fx',
    basePnL: 0,
    indicatorChanges: { usd: -1 },
    description: 'Gold window closed. End of Bretton Woods.',
    chain: 'Nixon ends gold convertibility → Dollar floats → Uncertainty spikes → Stable positions disrupted',
    art: '🪙',
    keywords: ['historical'],
    directEffect: 'stable_minus_2',
  },
];

// ─── Macro Desk (10 cards) ───────────────────────────────────

const MACRO_CARDS: CardDef[] = [
  {
    id: 'macro_covid',
    name: 'COVID Pandemic',
    desk: 'macro',
    type: 'catalyst',
    lane: 'any',
    basePnL: 0,
    indicatorChanges: { risk: -3, inflation: -1 },
    description: 'Everything stops. Global shutdown.',
    chain: 'Pandemic declared → Lockdowns imposed → Demand collapses → Deflation fears → Markets crash',
    art: '🦠',
    keywords: ['crisis'],
  },
  {
    id: 'macro_stimulus',
    name: 'COVID Stimulus',
    desk: 'macro',
    type: 'catalyst',
    lane: 'any',
    basePnL: 0,
    indicatorChanges: { rate: -1, inflation: 2, risk: 2 },
    description: 'The everything rally. Stimulus checks and QE.',
    chain: 'Trillions printed → Rates slashed → Liquidity floods → Asset prices inflate → Inflation follows',
    art: '💸',
    keywords: ['stimulus'],
  },
  {
    id: 'macro_bretton',
    name: 'Bretton Woods',
    desk: 'macro',
    type: 'catalyst',
    lane: 'any',
    basePnL: 0,
    description: 'Reset the world order. All indicators move toward neutral.',
    chain: 'New monetary framework → Exchange rates stabilized → Global order restored → Markets reset',
    art: '🌐',
    keywords: ['historical'],
    directEffect: 'reset_indicators',
  },
  {
    id: 'macro_elon',
    name: 'Elon Musk',
    desk: 'macro',
    type: 'position',
    lane: 'any',
    basePnL: 5,
    description: 'Chaos incarnate. Each turn: random indicator ±1.',
    chain: 'Musk tweets → Markets react → Nobody knows what\'s next → Volatility is the only certainty',
    art: '🚀',
    keywords: [],
    turnEffect: 'random_indicator',
  },
  {
    id: 'macro_sbf',
    name: 'SBF',
    desk: 'macro',
    type: 'position',
    lane: 'any',
    basePnL: 11,
    description: 'Huge P&L but 70% chance of destruction at quarter end. If destroyed: Risk −1.',
    chain: 'Leveraged empire built on sand → House of cards → Fraud revealed → Contagion spreads',
    art: '🃏',
    keywords: [],
    quarterEndEffect: 'destroy_70_risk',
  },
  {
    id: 'macro_war',
    name: 'War Economy',
    desk: 'macro',
    type: 'position',
    lane: 'any',
    basePnL: 3,
    sensitivities: {},
    description: 'Military spending boost. Grows +3/turn. If Inflation hits 5, destroyed.',
    chain: 'Defense spending surges → GDP boosted → But inflation overheats → Guns vs butter tradeoff',
    art: '⚔️',
    keywords: ['war'],
    turnEffect: 'growth_3',
  },
  {
    id: 'macro_regime',
    name: 'Regime Change',
    desk: 'macro',
    type: 'catalyst',
    lane: 'any',
    basePnL: 0,
    description: 'New paradigm. Swap Interest Rate and Inflation values.',
    chain: 'Policy regime shifts → Old correlations break → Markets reprice everything → New normal emerges',
    art: '🔄',
    keywords: [],
    directEffect: 'swap_rate_inflation',
  },
  {
    id: 'macro_sanctions',
    name: 'Sanctions',
    desk: 'macro',
    type: 'catalyst',
    lane: 'any',
    basePnL: 0,
    indicatorChanges: { usd: 1 },
    description: 'Freeze 1 opponent position for 2 turns. USD +1.',
    chain: 'Economic sanctions imposed → Assets frozen → Dollar demand spikes → Target isolated from markets',
    art: '🚫',
    keywords: ['geopolitical'],
    directEffect: 'freeze_opponent',
  },
  {
    id: 'macro_blackswan',
    name: 'Black Swan',
    desk: 'macro',
    type: 'position',
    lane: 'any',
    basePnL: 0,
    sensitivities: { risk: -4 },
    description: 'Tail risk bet. Massive profit from crisis, worthless otherwise.',
    chain: 'Out-of-the-money puts → Market crashes → Convexity kicks in → Asymmetric payoff',
    art: '🦢',
    keywords: [],
  },
  {
    id: 'macro_trump_tweet',
    name: 'Trump Tweet',
    desk: 'macro',
    type: 'catalyst',
    lane: 'any',
    basePnL: 0,
    description: 'Truth Social, 3am. Random indicator ±2.',
    chain: 'Presidential tweet → Markets scramble to interpret → Algorithms react → Volatility spikes',
    art: '📱',
    keywords: ['chaos'],
    directEffect: 'random_indicator_2',
  },
];

// ─── Export ──────────────────────────────────────────────────

export const ALL_CARDS: CardDef[] = [
  ...RATES_CARDS,
  ...EQUITIES_CARDS,
  ...COMMODITIES_CARDS,
  ...FX_CARDS,
  ...MACRO_CARDS,
];

export const CARD_MAP: Record<string, CardDef> = Object.fromEntries(
  ALL_CARDS.map(c => [c.id, c])
);

export function getCardsForDesk(desk: string): CardDef[] {
  return ALL_CARDS.filter(c => c.desk === desk);
}
